language: python
python:
  - "3.6"
install:
  - pip install -r requirements.txt
  - pip install python-coveralls
env:
  - SECRET_KEY=SK
script:
  - coverage run manage.py test
  - coverage report
after_success:
  - coveralls
