language: python
python:
  - "3.6"
services:
  - postgresql
  - docker
addons:
  postgresql: '12'
  apt:
    packages:
      - postgresql-12
      - postgresql-client-12
before_install:
  - sudo pg_dropcluster --stop 12 main
  - sudo pg_upgradecluster 11 main
  - sudo pg_ctlcluster 12 main restart
  - sudo pg_dropcluster 11 main
  - psql -c "CREATE DATABASE bothub;" -U postgres
  - psql -c "CREATE USER bothub WITH PASSWORD 'bothub';" -U postgres
install:
  - pip install pipenv
  - pipenv install --system --dev
  - pip install coveralls
  - python manage.py migrate
  - python manage.py collectstatic
env:
  global:
    - PGUSER=postgres
    - PGPORT=5432
    - SECRET_KEY=SK
    - SUPPORTED_LANGUAGES="en|pt"
    - DEFAULT_DATABASE="postgres://bothub:bothub@localhost:5432/bothub"
script:
  - flake8
  - travis_wait coverage run manage.py test
after_success:
  - coveralls
