language: python
python:
  - "3.6"
services:
  - docker
  - postgresql
before_script:
  - psql -c 'create database bothub' -U bothub
install:
  - pip install pipenv
  - pipenv install --system --dev
  - pip install coveralls
  - python manage.py migrate
  - python manage.py collectstatic
env:
  global:
    - PGUSER=bothub
    - PGPORT=5432
    - SECRET_KEY=SK
    - SUPPORTED_LANGUAGES="en|pt"
    - DEFAULT_DATABASE="postgres://bothub:@localhost:5432/bothub"
script:
  - flake8
  - travis_wait coverage run manage.py test
after_success:
  - coveralls
