language: python
python:
  - "3.6"
services:
  - docker
  - postgresql
addons:
  postgresql: '11'
  apt:
    packages:
      - postgresql-11
      - postgresql-client-11
      - postgresql-server-dev-11
before_install:
  - sudo pg_dropcluster --stop 12 main
  - sudo pg_upgradecluster 11 main
  - sudo pg_ctlcluster 12 main restart
  - sudo pg_dropcluster 11 main
  - psql -c 'create database bothub;' -U postgres
install:
  - pip install pipenv
  - pipenv install --system --dev
  - pip install coveralls
  - python manage.py migrate
  - python manage.py collectstatic
env:
  global:
    - PGUSER=postgres
    - PGPORT=5432
    - SECRET_KEY=SK
    - SUPPORTED_LANGUAGES="en|pt"
    - DEFAULT_DATABASE="postgres://bothub:@localhost:5432/bothub"
script:
  - flake8
  - travis_wait coverage run manage.py test
after_success:
  - coveralls
