version: '3.3'

services:
  bothub:
    image: ilha/bothub:latest
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - 8000:8000
    environment:
      - SECRET_KEY
      - DEBUG
      - ALLOWED_HOSTS
      - DEFAULT_DATABASE
      - LANGUAGE_CODE
      - TIME_ZONE
