version: '3.3'

services:
  bothub:
    image: $DOCKER_HUB_REPO:$TAG
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - 8000:8000
    environment:
      - SECRET_KEY
      - DEBUG
      - ALLOWED_HOSTS
      - DEFAULT_DATABASE
      - LANGUAGE_CODE
      - TIME_ZONE
      - ADMINS
      - DEFAULT_FROM_EMAIL
      - SERVER_EMAIL
      - EMAIL_HOST
      - EMAIL_PORT
      - EMAIL_HOST_USER
      - EMAIL_HOST_PASSWORD
      - EMAIL_USE_SSL
      - EMAIL_USE_TLS
      - BOTHUB_WEBAPP_BASE_URL
